defaultBaseImage: gcr.io/distroless/static-debian11:latest
builds:
  - env:
      - CGO_ENABLED=0
    flags:
      - '-v'
    ldflags:
      - '-s'
      - '-w'
defaultPlatforms:
  - linux/arm64
  - linux/amd64